backend:
  name: git-gateway
  branch: main

media_folder: "public/images/blog"
public_folder: "/images/blog"

# Configuració per a l'autenticació
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Articles del Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Descripció", name: "description", widget: "text"}
      - {label: "Data de publicació", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Imatge destacada", name: "featuredImage", widget: "image", required: false}
      - {label: "Categories", name: "categories", widget: "list", default: []}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Publicat", name: "published", widget: "boolean", default: true}
      - {label: "Contingut", name: "body", widget: "markdown"}